### ISSUE TITLE
\fmtord does not use upperscript letter when available

### ISSUE THREAD

**Issue by vincentb1** [nlct/fmtcount#16]
Dear @nlct,
Recently @dbitouze reported to me that `\fmtord` does not use upperscript letters when available. These glyphs are available with the `\up` command in the `frenchb` module of `babel`.

The consequence of this, is that the following will give a different aspect &mdash; please get the latest fmtcount before trying it, as I recently made a commit [d123fb1b1370f0e1de0cad3c141f5807e907b63a](https://github.com/nlct/fmtcount/commit/d123fb1b1370f0e1de0cad3c141f5807e907b63a):
```LaTeX
\documentclass[french]{minimal}
\usepackage{babel}
\usepackage{fmtcount}
\usepackage{array}
\usepackage[active,tightpage]{preview}
\begin{document}
\begin{preview}
  \begin{tabular}{@{ }l@{ }l@{ }}
    babel&fmtcount\\\hline
    1\ier&\ordinalnum{1}\\
    2\ieme&\ordinalnum{2}\\
  \end{tabular}
\end{preview}
\end{document}
```
You should get something like this:
![ecm](https://cloud.githubusercontent.com/assets/5001763/5035938/bb643b50-6b7b-11e4-8316-f0ff0f6bbda1.png)

**Comment by nlct** [comment]
I wouldn't call replacing a package with a better designed package as crushing everything. Some things can be kept. There are two issues here: (1) separating the language-dependent aspects into independently maintained modules and (2) writing a better designed package. It's possible to achieve both without renaming the package but my concern is that this may cause compatibility issues. Users tend to get a bit annoyed if they upgrade their package only to find that their document doesn't compile any more. If modifications can be made without breaking backward compatibility then I'm fine with not renaming the package. However, regardless of whether or not a new package is required, these changes, especially (1) need implementing.

Currently fmtcount supports English (UK), French, German and Spanish. (Italian support is just an interface to itnumpar.) How many more languages will be added or should we simply say, "no that's enough"? Each new language increases the amount of code that needs to be installed. At the moment, a user who only ever uses one language still has to install all the fmtcount language support, even though they don't need all of it. It's worth noting that babel has also followed this route of separating the languages into independent modules. Each module needs to be maintained by someone fluent in that language and who knows the styles relevant to that language.

The other advantage in separating the languages into separate modules is that they can be uploaded to CTAN independently. If an issue is fixed in one module, it can straight away be uploaded to CTAN and get into the TeX distributions even if there are still issues that need fixing in the other modules. That way the fix is available to users without having to wait for the other issues to be resolved.

If you really want to keep fmtcount as a single monolithic package, then I'll have to step down as maintainer as I already have several large time-consuming packages to maintain.

**Comment by vincentb1** [comment]
Dear Nicola,

I fully agree with your suggestion (1). Wouldn't it account basically to:
* rename `fc-xxxx.def` to `fmtcount-xxxx.sty`, 
* to edit its content in order to make it a package, ie notably add the `\ProvidesPackage{fmtcount-xxxx}` statement
* to load it with a `\RequirePackage`, rather than with an `\input`

Maybe that is not the full story: currently fmtcount tries to load languages on the fly with best effort &mdash; no guarantee to succeed &mdash; when the use of a language is detected within the document body, but the language has not been statically loaded. So probably, if we want to keep this feature we need to keep the `fc-xxxx.def` as it is, and make `fmtcount-xxxx.sty` just a wrapper/loader for it.

Concerning (2), I think that this is a long term task to improve fmtcount, not only with respect to language independance. No revolution here. For instance with the correction of this issue #16, I have pushed some of the French specific code from `fmtcount.sty` to `fc-french.def`, which goes in the right direction.

&nbsp;&nbsp;&nbsp;Vincent.

**Comment by nlct** [comment]
Hi Vincent,

We could adopt the approach I've used in the new datetime2 package. This first loads tracklang

    \RequirePackage{tracklang}

This will pick up any language options the user has passed through the document class options list and it will also check for babel, polyglossia, translator and ngerman, and will pick up the requested languages from them (provided they have already been loaded). The main drawbacks are that tracklang can only pick up the root language not the regional variant from polyglossia and the user has to use `\setmainlanguage` and `\setotherlanguage` before tracklang is loaded. However, for the most part this is the simplest way of determining which languages the document uses. Additionally datetime2 passes any unknown options to tracklang using something like

    \DeclareOption*{\TrackPredefinedDialect{\CurrentOption}}

So now the user can also specify the required languages in the package option list, if they want. The actual loading of the language dependent code is done using something like:

    \AnyTrackedLanguages
    {%
      \ForEachTrackedDialect{\this@dialect}%
     {%
        \@dtm@requiremodule\this@dialect
      }%
    }
    {%
      % no languages detect, apply some default setting
    }

For fmtcount we'd need to replace datetime2's `\@dtm@requiremodule` with, say, `\@fmt@requiremodule`. (The commands `\AnyTrackedLanguages` and `\ForEachTrackedDialect` are provided by tracklang.) The `\@dtm@requiremodule` bit is defined as

    \newcommand*{\@dtm@requiremodule}[1]{%
      \IfTrackedLanguageFileExists{#1}%
      {datetime2-}% prefix
      {.ldf}% suffix
      {%
        \RequireDateTimeModule{\CurrentTrackedTag}%
      }%
      {%
        \@dtm@warning{Date-Time Language Module `#1' not installed}%
      }%
    }

We could adapt that for fmtcount using something like:

    \newcommand*{\@fmt@requiremodule}[1]{%
      \IfTrackedLanguageFileExists{#1}%
      {fc-}% prefix
      {.def}% suffix
      {%
        \RequireFmtCountModule{\CurrentTrackedTag}%
      }%
      {%
        \PackageWarning{fmtcount}{fmtcount Language Module `#1' not installed}%
      }%
    }

The `\RequireFmtCountModule` works in a similar manner to `\RequirePackage`. It prevents the file from being input if it's already been loaded. We can adapt the datetime2 command to something like:

    \newcommand*{\RequireFmtCountModule}[1]{%
      \ifundef\CurrentTrackedDialect
      {%
        \PackageError{fmtcount}%
        {\string\RequireFmtCountModule\space not permitted here}%
        {This command is only permitted inside fmtcount language
        modules.}%
     }%
     {%
       \ifcsundef{ver@fc-#1.def}%
       {%
         \input{fc-#1.def}%
       }%
       {}%
     }%
    }

The fc-xxxx.def files already identify themselves with `\ProvidesFCLanguage` so that replaces the equivalent `\ProvidesDateTimeModule` in datetime2.

The `\IfTrackedLanguageFileExists` bit (from tracklang) is the really useful one as then we don't need to worry about which of the various language synonyms that the user has used (for example, `UKenglish` or `british` or `USenglish` or `american`).

**Comment by vincentb1** [comment]
Hello,
After delivering v3.01 to CTAN, I close this issue, further discussion about language management improvement should go in another thread&hellip;
